version: "1.0"

services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - ./api/db/postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres_user -d exchangeRates'"]
      interval: 10s
      timeout: 3s
      retries: 3

  api:
    build: ./api
    restart: always
    volumes:
      - ./api:/api
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy

  bot:
    build: ./telegram_bot
    restart: always
    volumes:
      - ./telegram_bot:/bot
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      api:
        condition: service_started
