"""Add wallet_number to Wallet model

Revision ID: b3d402749ac2
Revises: b46db317e9c9
Create Date: 2024-06-03 09:02:30.000075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d402749ac2'
down_revision = 'b46db317e9c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_number', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['wallet_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('wallet_number')

    # ### end Alembic commands ###
